name: UltraPlaytime
version: '${project.version}'
main: net.pinodev.ultraplaytime.UltraPlaytime
api-version: '1.16'
softdepend:
  - PlaceholderAPI
commands:
  playtime:
    description: "Check your playtime"
    permission: "ultraplaytime.playtime"
    aliases:
      - ptime
      - ultraplaytime
  playtimeadmin:
    description: "Administrator commands"
    permission: "ultraplaytime.admin"
    aliases:
      - ptimeadmin
      - uptimeadmin